title: beehome
tagline: tagline
description: 展开得意的手掌,却是破碎的金黄.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://beehome.org # the base hostname & protocol for your site

author:
  name: yourname
  email: youremail
  github: githubhere
  twitter: ttee
  weibo: weiboma

permalink: /:year/:month/:day/:title
timezone: Asia/Shanghai

tags_path: /tags.html
feed_path: /feed.xml

markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

service:
  comment: disqus
  disqus:
    short_name: evercoding
  duoshuo: 
    short_name: evercoding
  google:
    tracking_id : 
  baidu:
    num: 

exclude: [README.md, CNAME]
  
